// Regenerates short.md from slides.md so the two can never drift.
// The short deck is a SELECTION plus two edits, nothing hand-written:
//   - Why Now drops its pull-quotes; they need a speaker to land.
//   - Every page loses its clicks: a leave-behind has no presenter to advance
//     it, so whatever a beat would have revealed is simply shown.
// Run: npm run short
//
// Insight used to be split here, one SDLC stage per page. slides.md now ships
// it split, so this takes both pages as they are. Same for Why Now, which is
// two pages in the full deck; the short deck keeps the one with the figures.
const fs = require('fs')
const path = require('path')
const dir = path.join(__dirname, '..')

const src = fs.readFileSync(path.join(dir, 'slides.md'), 'utf8')
const lines = src.split('\n')
const seps = lines.flatMap((l, i) => (l.trim() === '---' ? [i] : []))
const blocks = []
let prev = 0
for (const i of [...seps, lines.length]) { blocks.push(lines.slice(prev, i).join('\n')); prev = i + 1 }

const eyebrowOf = (b) => (b.match(/class="eyebrow"[^>]*>\s*([^<]+)/) || [, ''])[1].trim()
const pick = (i, expect) => {
  const got = eyebrowOf(blocks[i])
  if (!got.includes(expect)) throw new Error(`block ${i}: expected "${expect}", found "${got}" — slides.md order changed`)
  return blocks[i]
}

const FRONTMATTER = blocks[1]
const COVER = blocks[2]
const PROBLEM   = pick(3, 'The Problem')
const SOLUTION  = pick(4, 'The Solution')
const INSIGHT_F = pick(5, 'The Insight')   // the human loop
const INSIGHT_G = pick(6, 'The Insight')   // the Cambra loop
const WHYNOW    = pick(7, 'Why Now')       // the figures; page two is the quotes
const TEAM      = pick(9, 'Team')
const MARKET    = pick(10, 'Market')  // categories
const SEGMENTS  = pick(11, 'Market')  // segments — the payoff of the one above
const BIZ       = pick(16, 'Business Model')
const ASK       = pick(17, 'The Ask')

// --- Insight: both pages, minus their clicks -----------------------------
// A leave-behind has nobody to press the button, so every beat is shown.
const unclick = (b) => b.replace(/ v-click=("?)[^"\s>]+\1/g, '')
const INSIGHT_A = unclick(INSIGHT_F)
const INSIGHT_B = unclick(INSIGHT_G)

// --- Why Now: drop the pull-quotes, then close the click gaps they left ---
let WHYNOW_S = WHYNOW.replace(/ *<QuoteCard[\s\S]*?\/>\n/g, '')
                     .replace(/ *<div v-click="2"><\/div>\n/g, '')
let trend = 0
WHYNOW_S = WHYNOW_S.replace(/<div class="trend" v-click=("?)\d\1>/g, () => `<div class="trend" v-click="${++trend}">`)
if (trend !== 3) throw new Error(`Why Now: restaged ${trend} trends, expected 3`)

const PAGES = [COVER, PROBLEM, SOLUTION, INSIGHT_A, INSIGHT_B, WHYNOW_S, TEAM, MARKET, SEGMENTS, BIZ, ASK]
// Insight's two pages share a number, and so do the two market pages.
const NUMBERS = [null, 1, 2, 3, 3, 4, 5, 6, 6, 7, 8]
const renumbered = PAGES.map((b, i) =>
  NUMBERS[i] == null ? b : b.replace(/(class="eyebrow"[^>]*>\s*)\d\d( · )/, `$1${String(NUMBERS[i]).padStart(2, '0')}$2`))

const HEADER = `<!-- GENERATED by scripts/make-short.cjs from slides.md — do not edit by hand.
     Run \`npm run short\` after changing slides.md. -->`
fs.writeFileSync(path.join(dir, 'short.md'), [FRONTMATTER, HEADER + '\n' + renumbered[0], ...renumbered.slice(1)]
  .join('\n---\n').replace(/^/, '---\n') + '\n')
console.log('short.md regenerated:', renumbered.length, 'pages')
