// Regenerates short.md from slides.md so the two can never drift.
// The short deck is a SELECTION plus three edits, nothing hand-written:
//   - Insight is split in two, each pinned to one SDLC stage, so the human
//     loop and the Cambra loop each get a page instead of a click.
//   - Why Now drops its pull-quotes; they need a speaker to land.
//   - Eyebrows renumber to the short deck's own sequence.
// Run: npm run short
const fs = require('fs')
const path = require('path')
const dir = path.join(__dirname, '..')

const src = fs.readFileSync(path.join(dir, 'slides.md'), 'utf8')
const lines = src.split('\n')
const seps = lines.flatMap((l, i) => (l.trim() === '---' ? [i] : []))
const blocks = []
let prev = 0
for (const i of [...seps, lines.length]) { blocks.push(lines.slice(prev, i).join('\n')); prev = i + 1 }

const eyebrowOf = (b) => (b.match(/class="eyebrow"[^>]*>\s*([^<]+)/) || [, ''])[1].trim()
const pick = (i, expect) => {
  const got = eyebrowOf(blocks[i])
  if (!got.includes(expect)) throw new Error(`block ${i}: expected "${expect}", found "${got}" — slides.md order changed`)
  return blocks[i]
}

const FRONTMATTER = blocks[1]
const COVER = blocks[2]
const PROBLEM  = pick(3, 'The Problem')
const SOLUTION = pick(4, 'The Solution')
const INSIGHT  = pick(5, 'The Insight')
const WHYNOW   = pick(6, 'Why Now')
const TEAM     = pick(7, 'Team')
const MARKET   = pick(8, 'Market')   // categories
const SEGMENTS = pick(9, 'Market')   // segments — the payoff of the one above
const BIZ      = pick(14, 'Business Model')
const ASK      = pick(15, 'The Ask')

// --- Insight: one page per loop, each pinned to a stage -------------------
const insightPage = (stage, keepBeat, closer) => {
  let b = INSIGHT
    .replace(/<SdlcDiagram :stage="\$clicks \+ 1" \/>/, `<SdlcDiagram :stage="${stage}" fixed />`)
    .replace(/<div class="closer center"[^>]*>[\s\S]*?<\/div>/, `<div class="closer center">${closer}</div>`)
  // Keep only this page's half of the Today/Cambra pair, always visible.
  const beats = [...b.matchAll(/ *<div v-click="\d"><b>(Today|Cambra)<\/b>[\s\S]*?<\/div>\n/g)]
  for (const m of beats) if (!m[0].includes(`<b>${keepBeat}</b>`)) b = b.replace(m[0], '')
  return b.replace(/ v-click="\d"(?=><b>(?:Today|Cambra)<\/b>)/g, '')
}
const INSIGHT_A = insightPage(3, 'Today', 'Today a <span class="hot">human</span> closes the loop.')
const INSIGHT_B = insightPage(4, 'Cambra', "You can't bolt this on. <span class=\"warm\">You have to design it in.</span>")

// --- Why Now: drop the pull-quotes, then close the click gaps they left ---
let WHYNOW_S = WHYNOW.replace(/ *<QuoteCard[\s\S]*?\/>\n/g, '')
                     .replace(/ *<div v-click="2"><\/div>\n/g, '')
let trend = 0
WHYNOW_S = WHYNOW_S.replace(/<div class="trend" v-click=("?)\d\1>/g, () => `<div class="trend" v-click="${++trend}">`)
if (trend !== 3) throw new Error(`Why Now: restaged ${trend} trends, expected 3`)

const PAGES = [COVER, PROBLEM, SOLUTION, INSIGHT_A, INSIGHT_B, WHYNOW_S, TEAM, MARKET, SEGMENTS, BIZ, ASK]
// Insight's two pages share a number, and so do the two market pages.
const NUMBERS = [null, 1, 2, 3, 3, 4, 5, 6, 6, 7, 8]
const renumbered = PAGES.map((b, i) =>
  NUMBERS[i] == null ? b : b.replace(/(class="eyebrow"[^>]*>\s*)\d\d( · )/, `$1${String(NUMBERS[i]).padStart(2, '0')}$2`))

const HEADER = `<!-- GENERATED by scripts/make-short.cjs from slides.md — do not edit by hand.
     Run \`npm run short\` after changing slides.md. -->`
fs.writeFileSync(path.join(dir, 'short.md'), [FRONTMATTER, HEADER + '\n' + renumbered[0], ...renumbered.slice(1)]
  .join('\n---\n').replace(/^/, '---\n') + '\n')
console.log('short.md regenerated:', renumbered.length, 'pages')
